<?php
    
    require 'inc/session_check.php';
    require 'inc/config.php';
    require 'inc/crypt.php';  
    
    //Current time zone
	date_default_timezone_set('Asia/Calcutta');    
    $currentDate = date("Y-m-d H:i:s");    
    
    $autoGeneratedToken = md5(rand(1,99)).md5('huseven');
    
        
    
    
    //Get Sub Sub Categories Admin Index
    if(isset($_POST['action']) && $_POST['action'] == "getsubcategoriesindex") {
    	$secondproductcatid = $_POST['secondproductcatid']; 
        $query=$conn->query("SELECT sid, sname FROM subcategories WHERE cid = '$secondproductcatid'");
        $count=$query->num_rows; 
        
        if($count > 0) { 
                    
            foreach($query as $row) { 
                    
                echo "                                  
                    <option value='".$row['sid']."'>".ucwords($row['sname'])."</option>
                "; 
            }                      
        
        }else {
            
                echo "
                        <option value=''>No Sub Category</option>
                 ";
        }
    }
    
    //Get Sub Sub Categories Admin Index
    if(isset($_POST['action']) && $_POST['action'] == "getfrsubcategoriesindex1") {
    	$secondproductcatid = $_POST['secondproductcatid']; 
        $query=$conn->query("SELECT sid, sname FROM subcategories WHERE cid = '$secondproductcatid'");
        $count=$query->num_rows; 
        
        if($count > 0) { 
                echo "
                        <option value='0'>Select Category</option>
                 ";       
            foreach($query as $row) { 
                    
                echo "                                  
                    <option value='".$row['sid']."'>".ucwords($row['sname'])."</option>
                "; 
            }                      
        
        }else {
            
                echo "
                        <option value=''>No Sub Category</option>
                 ";
        }
    }    
    if(isset($_POST['action']) && $_POST['action'] == "getfrsubcategoriesindex2") {
    	$thirdproductcatid = $_POST['thirdproductcatid']; 
        $query=$conn->query("SELECT ssid, ssname FROM subsubcategories WHERE sid = '$thirdproductcatid'");
        $count=$query->num_rows; 
        
        if($count > 0) {
                    
            foreach($query as $row) { 
                    
                echo "                                  
                    <option value='".$row['ssid']."'>".ucwords($row['ssname'])."</option>
                "; 
            }                      
        
        }else {
            
                echo "
                        <option value=''>No Sub Category</option>
                 ";
        }
    }   
    
    
    
    
    
    
    
    
    
    //Product Page Categories
    if(isset($_POST['action']) && $_POST['action'] == "getprofirstcategories") {
    	$profirstcat = $_POST['profirstcat'];
        $query=$conn->query("SELECT sid, cid, sname FROM subcategories WHERE cid = '$profirstcat'");
        $count=$query->num_rows; 
        
        if($count > 0) { 
                echo "
                        <option value='0'>Select Category</option>
                 ";     
            foreach($query as $row) { 
                    
                echo "                                  
                    <option value='".$row['sid']."'>".ucwords($row['sname'])."</option>
                "; 
            }                      
        
        }else {
            
                echo "
                        <option value='0'>No Sub Category</option>
                 ";
        }
    }
    
    if(isset($_POST['action']) && $_POST['action'] == "getprosecondcategories") {
    	$prosecondcat = $_POST['prosecondcat'];
        $query=$conn->query("SELECT ssid, sid, cid, ssname FROM subsubcategories WHERE sid = '$prosecondcat'");
        $count=$query->num_rows; 
        
        if($count > 0) { 
                echo "
                        <option value='0'>Select Category</option>
                 ";     
            foreach($query as $row) { 
                    
                echo "                                  
                    <option value='".$row['ssid']."'>".ucwords($row['ssname'])."</option>
                "; 
            }                      
        
        }else {
            
                echo "
                        <option value='0'>No Sub Category</option>
                 ";
        }
    }
    
    if(isset($_POST['action']) && $_POST['action'] == "getprothirdcategories") {
    	$prothirdcat = $_POST['prothirdcat'];
        $query=$conn->query("SELECT sssid, sssname FROM subsubsubcategories WHERE ssid = '$prothirdcat'");
        $count=$query->num_rows; 
        
        if($count > 0) { 
                   
            foreach($query as $row) { 
                    
                echo "                                  
                    <option value='".$row['sssid']."'>".ucwords($row['sssname'])."</option>
                "; 
            }                      
        
        }else {
            
                echo "
                        <option value='0'>No Sub Category</option>
                 ";
        }
    }
    
    
    
    
    if(isset($_POST['action']) && $_POST['action'] == "productdesc") {
        
        $apid       = $_POST["apid"];
        $procatname = $_POST["procatname"];
        $prosubcatname = $_POST["prosubcatname"];
        $prosubsubcatname = $_POST["prosubsubcatname"];
        $prosubsubsubcatname = $_POST["prosubsubsubcatname"];
        $protitle = $conn->real_escape_string($_POST["protitle"]);  
        $proname = $conn->real_escape_string($_POST["proname"]);     
        $prodesc = $conn->real_escape_string($_POST['prodesc']);
        $brandname = $conn->real_escape_string($_POST["probrandname"]); 
        $proprice = $_POST["proprice"];        
        $protype = $_POST["protype"];
        $getdispanel1 = $_POST["getdispanel1"];
        $prodistype = $_POST["prodistype"];
        $prodisprice = $_POST["prodisprice"];
        $pronetprice = $_POST["pronetprice"];
        $proqty = $_POST["proqty"];        
        $cashondelivery1 = $_POST["cashondelivery1"];
        $returnproduct1 = $_POST["returnproduct1"];
        $prostatus  = $_POST["prostatus"];
        $feature_products1 = $_POST["feature_products1"];
        $istatus = $_POST["istatus"];
        
        $dis_ifrupeeselected = 0;
        if($prodistype == 1) {
            $dis_ifrupeeselected = ($prodisprice / $proprice) * 100;
        }
        if($prodistype == 2) {
            $dis_ifrupeeselected = $prodisprice;
        }
          
                     
        //Rows
        if(!empty($_POST["totalrows"])){
            $totalrows = $_POST["totalrows"];
        }
        if(!empty($_POST["attribute_name"])){
            $attribute_name = $_POST["attribute_name"];
        }
        if(!empty($_POST["attribute_value"])){
            $attribute_value = $_POST["attribute_value"];
        }
    
        if(empty($getdispanel1)) {
            $getdispanel1 = '0';
        }
        if(empty($prodisprice)) {
            $prodisprice = '0';
        }
        
        if(empty($cashondelivery1)) {
            $cashondelivery1 = '0';
        }
        if(empty($returnproduct1)) {
            $returnproduct1 = '0';
        }
        if(empty($feature_products1)) {
            $feature_products1 = '0';
        }
           $vid=$_SESSION['vuserid'];  
        if(empty($apid)) {
        //insert        
       
        $conn->query("INSERT INTO `product_details` (`cid`, `sid`, `ssid`, `sssid`, `product_title`, product_name, `brand_name`,
                     `gross_price`, `is_discounted_product`, `dis_type`, `discount_price`, `net_price`, `quantity`, 
                     `product_status`, `dated`, `uploaded_by`, product_discount, `description`, 
                     `eligible_for_cash_on_delivery`, `product_return_allowed`, product_type, feature_products, status, vendorid ,venderprice) VALUES ('$procatname', '$prosubcatname', '$prosubsubcatname', '$prosubsubsubcatname', '$protitle', '$proname', '$brandname', 
                      '$proprice', '$getdispanel1', '$prodistype', '$prodisprice', '$pronetprice',
                      '$proqty', '$protype', '$currentDate', '".$_SESSION['auserid']."', '$dis_ifrupeeselected', '$prodesc', '$cashondelivery1', '$returnproduct1', '$prostatus', '$feature_products1', '$istatus', '".$_SESSION['vuserid']."','$pronetprice')");
             
        //$conn->query("INSERT INTO `product_details` (`catid`, `subcatid`, `subsubcatid`, `product_title`, `product_name`, `gross_price`, `unitname`, `is_discounted_product`, `dis_type`, `discount_price`, `net_price`, `quantity`, `product_status`, dated, uploaded_by, size, brand_name, product_discount, delivered_24_7) VALUES ('".$procatname."', '".$prosubcatname."', '".$prosubsubcatname."', '".$protitle."', '".$proname."', '".$proprice."', '".$prounit."', '".$getdispanel1."', '".$prodistype."', '".$prodisprice."', '".$pronetprice."', '".$proqty."', '".$protype."', '".$currentdate."', '".$_SESSION['suserid']."', '".$size."', '".$brandname."', '".$dis_ifrupeeselected."', '$getdelivered247');");
        
        $lastInsertedID =  $conn->insert_id;
  		
    	if($conn->affected_rows > 0){
    	             
           for($i=0;$i<=$totalrows;$i++) {
                if( !empty($_POST["attribute_name"][$i]) && !empty($_POST["attribute_value"][$i]) ) {
                    $conn->query("INSERT INTO product_spec_details (`proid`, `attribute_name`, `attribute_value`) VALUES ('$lastInsertedID', '".$conn->real_escape_string($_POST["attribute_name"][$i])."', '".$conn->real_escape_string($_POST["attribute_value"][$i])."');");
                }
           }
        }
        $imid = $lastInsertedID;
        }else {
        //update
        
        
        $conn->query("UPDATE `product_details` SET `cid`='$procatname', `sid`='$prosubcatname', `ssid`='$prosubsubcatname', `sssid`='$prosubsubsubcatname',
        `product_title`='$protitle', `brand_name`='$brandname', `gross_price`='$proprice', `is_discounted_product`='$getdispanel1', 
        `dis_type`='$prodistype', `discount_price`='$prodisprice', `net_price`='$pronetprice', `quantity`='$proqty', 
        `product_status`='$protype', `dated`='$currentDate', `uploaded_by`='".$_SESSION['auserid']."', 
        `product_discount`='$dis_ifrupeeselected', `description`='$prodesc', 
        `eligible_for_cash_on_delivery`='$cashondelivery1', `product_return_allowed`='$returnproduct1',
         product_type = '$prostatus', feature_products = '$feature_products1', status='$istatus'
         WHERE `proid`='$apid'");
        //$conn->query("UPDATE `product_details` SET `catid`='".$procatname."', `subcatid`='".$prosubcatname."', `subsubcatid`='".$prosubsubcatname."', `product_title`='".$protitle."', `product_name`='".$proname."', `gross_price`='".$proprice."', `unitname`='".$prounit."', `is_discounted_product`='".$getdispanel1."', `dis_type`='".$prodistype."', `discount_price`='".$prodisprice."', `net_price`='".$pronetprice."', `quantity`='".$proqty."', `product_status`='".$protype."', `dated`='".$currentdate."', `uploaded_by`='".$_SESSION['suserid']."', `size`='".$size."', `brand_name`='".$brandname."', delivered_24_7='$getdelivered247' WHERE `proid`='".$proid."'");
    	
        
    	if($conn->affected_rows > 0){
    	              
           $q1=$conn->query("select pro_specid from product_spec_details where proid = '".$apid."'");
           while($r1=$q1->fetch_array()) {
            
            $conn->query("DELETE FROM `product_spec_details` WHERE `pro_specid`='".$r1['pro_specid']."'");
           }
           
           
           for($i=0;$i<=$totalrows;$i++) {
            if( !empty($_POST["attribute_name"][$i]) && !empty($_POST["attribute_value"][$i]) ) {
                $conn->query("INSERT INTO product_spec_details (`proid`, `attribute_name`, `attribute_value`) VALUES ('$apid', '".$conn->real_escape_string($_POST["attribute_name"][$i])."', '".$conn->real_escape_string($_POST["attribute_value"][$i])."');");
            }
           }
    	
        }
           $imid = $apid; 
        }
        
        
         $_dir = 'uploads/'.$imid.'/';        
            //Make Directories           
            if(!file_exists($_dir)) {
                   mkdir($_dir, 0777, true);
            } 
        
        if($_FILES['proimg']['name']!='')
        {        
                         
            $tmp_name = $_FILES["proimg"]["tmp_name"];
            $namefile = $_FILES["proimg"]["name"];
			$ext = end(explode(".", $namefile));
			$image_name=time().".".$ext;
            
            $path_parts = pathinfo($_FILES['proimg']['name']);
    
            $DirName_Dot = $path_parts['dirname'];
            $FileWithExt = $path_parts['basename'];
            $FileExt = $path_parts['extension'];
            $FileWithoutName = $path_parts['filename']; 
            
            $modifiedFileName = $imid . '.'.  $FileExt;
            
            $sourcePath = $_FILES['proimg']['tmp_name']; 
            $targetPath = $_dir.$modifiedFileName; 
            move_uploaded_file($sourcePath,$targetPath) ; 
                
            $conn->query("UPDATE product_details SET product_image='$targetPath' WHERE proid='".$imid."';");
        }
        
        
        if( (isset($_FILES['related_images']['name'])) && ($_FILES["related_images"]["name"]) != '' )
            {
                      
                
                $file_name_all="";
                for($i=0; $i<count($_FILES['related_images']['name']); $i++) 
                {
                   $tmpFilePath = $_FILES['related_images']['tmp_name'][$i];    
                   if ($tmpFilePath != "")
                   {    
                  
                       $name = $_FILES['related_images']['name'][$i];
                       $size = $_FILES['related_images']['size'][$i];
       
                       list($txt, $ext) = explode(".", $name);
                       //$file= time().substr(str_replace(" ", "_", $txt), 0);
                       $file= substr(str_replace(" ", "_", $txt), 0);
                       $info = pathinfo($file);
                       $filename = $file.".".$ext;
                       $modifiedFileName = $_dir . $filename;
                       if(move_uploaded_file($_FILES['related_images']['tmp_name'][$i], $_dir.$filename)) 
                       { 
                          date_default_timezone_set ("Asia/Calcutta");
                          $currentdate=date("d M Y");
                          //$file_name_all.=$filename."*";
                          $conn->query("INSERT into product_images (`proid`, `pro_images`) VALUES('".$imid."', '".addslashes($modifiedFileName)."'); ");
                       }
                   }
                //$filepath = rtrim($file_name_all, '*');              
                }           
            }
            
            echo 'productupdated';
   
    } 
    
    
    if(isset($_POST['action']) && $_POST['action'] == "vendorproductdesc") {
        
        $apid       = $_POST["apid"];
        $procatname = $_POST["procatname"];
        $prosubcatname = $_POST["prosubcatname"];
        $prosubsubcatname = $_POST["prosubsubcatname"];
        $prosubsubsubcatname = $_POST["prosubsubsubcatname"];
        $protitle = $conn->real_escape_string($_POST["protitle"]);  
        $proname = $conn->real_escape_string($_POST["proname"]);     
        $prodesc = $conn->real_escape_string($_POST['prodesc']);
        $brandname = $conn->real_escape_string($_POST["probrandname"]); 
        $proprice = $_POST["proprice"];        
        $protype = $_POST["protype"];
        $getdispanel1 = $_POST["getdispanel1"];
        $prodistype = $_POST["prodistype"];
        $prodisprice = $_POST["prodisprice"];
        $pronetprice = $_POST["pronetprice"];
        $proqty = $_POST["proqty"];        
        $cashondelivery1 = $_POST["cashondelivery1"];
        $returnproduct1 = $_POST["returnproduct1"];
        $prostatus  = $_POST["prostatus"];
        $feature_products1 = $_POST["feature_products1"];
        
        
        $dis_ifrupeeselected = 0;
        if($prodistype == 1) {
            $dis_ifrupeeselected = ($prodisprice / $proprice) * 100;
        }
        if($prodistype == 2) {
            $dis_ifrupeeselected = $prodisprice;
        }
          
                     
        //Rows
        if(!empty($_POST["totalrows"])){
            $totalrows = $_POST["totalrows"];
        }
        if(!empty($_POST["attribute_name"])){
            $attribute_name = $_POST["attribute_name"];
        }
        if(!empty($_POST["attribute_value"])){
            $attribute_value = $_POST["attribute_value"];
        }
    
        if(empty($getdispanel1)) {
            $getdispanel1 = '0';
        }
        if(empty($prodisprice)) {
            $prodisprice = '0';
        }
        
        if(empty($cashondelivery1)) {
            $cashondelivery1 = '0';
        }
        if(empty($returnproduct1)) {
            $returnproduct1 = '0';
        }
        if(empty($feature_products1)) {
            $feature_products1 = '0';
        }
               
        if(empty($apid)) {
        //insert        
        
        $conn->query("INSERT INTO `product_details` (`cid`, `sid`, `ssid`, `sssid`, `product_title`, product_name, `brand_name`,
                     `gross_price`, `is_discounted_product`, `dis_type`, `discount_price`, `net_price`, `quantity`, 
                     `product_status`, `dated`, `uploaded_by`, product_discount, `description`, 
                     `eligible_for_cash_on_delivery`, `product_return_allowed`, product_type, feature_products, status, vendorid) VALUES ('$procatname', '$prosubcatname', '$prosubsubcatname', '$prosubsubsubcatname', '$protitle', '$proname', '$brandname', 
                      '$proprice', '$getdispanel1', '$prodistype', '$prodisprice', '$pronetprice',
                      '$proqty', '$protype', '$currentDate', '".$_SESSION['vuserid']."', '$dis_ifrupeeselected', '$prodesc', '$cashondelivery1', '$returnproduct1', '$prostatus', '$feature_products1', 'InActive', '".$_SESSION['vuserid']."')");
             
        //$conn->query("INSERT INTO `product_details` (`catid`, `subcatid`, `subsubcatid`, `product_title`, `product_name`, `gross_price`, `unitname`, `is_discounted_product`, `dis_type`, `discount_price`, `net_price`, `quantity`, `product_status`, dated, uploaded_by, size, brand_name, product_discount, delivered_24_7) VALUES ('".$procatname."', '".$prosubcatname."', '".$prosubsubcatname."', '".$protitle."', '".$proname."', '".$proprice."', '".$prounit."', '".$getdispanel1."', '".$prodistype."', '".$prodisprice."', '".$pronetprice."', '".$proqty."', '".$protype."', '".$currentdate."', '".$_SESSION['suserid']."', '".$size."', '".$brandname."', '".$dis_ifrupeeselected."', '$getdelivered247');");
        
        $lastInsertedID =  $conn->insert_id;
  		
    	if($conn->affected_rows > 0){
    	             
           for($i=0;$i<=$totalrows;$i++) {
                if( !empty($_POST["attribute_name"][$i]) && !empty($_POST["attribute_value"][$i]) ) {
                    $conn->query("INSERT INTO product_spec_details (`proid`, `attribute_name`, `attribute_value`) VALUES ('$lastInsertedID', '".$conn->real_escape_string($_POST["attribute_name"][$i])."', '".$conn->real_escape_string($_POST["attribute_value"][$i])."');");
                }
           }
        }
        $imid = $lastInsertedID;
        }else {
        //update
        
        
        $conn->query("UPDATE `product_details` SET `cid`='$procatname', `sid`='$prosubcatname', `ssid`='$prosubsubcatname', `sssid`='$prosubsubsubcatname',
        `product_title`='$protitle', `brand_name`='$brandname', `gross_price`='$proprice', `is_discounted_product`='$getdispanel1', 
        `dis_type`='$prodistype', `discount_price`='$prodisprice', `net_price`='$pronetprice', `quantity`='$proqty', 
        `product_status`='$protype', `dated`='$currentDate', `uploaded_by`='".$_SESSION['vuserid']."', 
        `product_discount`='$dis_ifrupeeselected', `description`='$prodesc', 
        `eligible_for_cash_on_delivery`='$cashondelivery1', `product_return_allowed`='$returnproduct1',
         product_type = '$prostatus', feature_products = '$feature_products1', status='InActive', vendorid='".$_SESSION['vuserid']."'
         WHERE `proid`='$apid'");
        //$conn->query("UPDATE `product_details` SET `catid`='".$procatname."', `subcatid`='".$prosubcatname."', `subsubcatid`='".$prosubsubcatname."', `product_title`='".$protitle."', `product_name`='".$proname."', `gross_price`='".$proprice."', `unitname`='".$prounit."', `is_discounted_product`='".$getdispanel1."', `dis_type`='".$prodistype."', `discount_price`='".$prodisprice."', `net_price`='".$pronetprice."', `quantity`='".$proqty."', `product_status`='".$protype."', `dated`='".$currentdate."', `uploaded_by`='".$_SESSION['suserid']."', `size`='".$size."', `brand_name`='".$brandname."', delivered_24_7='$getdelivered247' WHERE `proid`='".$proid."'");
    	
        
    	if($conn->affected_rows > 0){
    	              
           $q1=$conn->query("select pro_specid from product_spec_details where proid = '".$apid."'");
           while($r1=$q1->fetch_array()) {
            
            $conn->query("DELETE FROM `product_spec_details` WHERE `pro_specid`='".$r1['pro_specid']."'");
           }
           
           
           for($i=0;$i<=$totalrows;$i++) {
            if( !empty($_POST["attribute_name"][$i]) && !empty($_POST["attribute_value"][$i]) ) {
                $conn->query("INSERT INTO product_spec_details (`proid`, `attribute_name`, `attribute_value`) VALUES ('$apid', '".$conn->real_escape_string($_POST["attribute_name"][$i])."', '".$conn->real_escape_string($_POST["attribute_value"][$i])."');");
            }
           }
    	
        }
           $imid = $apid; 
        }
        
        
         $_dir = 'uploads/'.$imid.'/';        
            //Make Directories           
            if(!file_exists($_dir)) {
                   mkdir($_dir, 0777, true);
            } 
        
        if($_FILES['proimg']['name']!='')
        {        
                         
            $tmp_name = $_FILES["proimg"]["tmp_name"];
            $namefile = $_FILES["proimg"]["name"];
			$ext = end(explode(".", $namefile));
			$image_name=time().".".$ext;
            
            $path_parts = pathinfo($_FILES['proimg']['name']);
    
            $DirName_Dot = $path_parts['dirname'];
            $FileWithExt = $path_parts['basename'];
            $FileExt = $path_parts['extension'];
            $FileWithoutName = $path_parts['filename']; 
            
            $modifiedFileName = $imid . '.'.  $FileExt;
            
            $sourcePath = $_FILES['proimg']['tmp_name']; 
            $targetPath = $_dir.$modifiedFileName; 
            move_uploaded_file($sourcePath,$targetPath) ; 
                
            $conn->query("UPDATE product_details SET product_image='$targetPath' WHERE proid='".$imid."';");
        }
        
        
        if( (isset($_FILES['related_images']['name'])) && ($_FILES["related_images"]["name"]) != '' )
            {
                      
                
                $file_name_all="";
                for($i=0; $i<count($_FILES['related_images']['name']); $i++) 
                {
                   $tmpFilePath = $_FILES['related_images']['tmp_name'][$i];    
                   if ($tmpFilePath != "")
                   {    
                  
                       $name = $_FILES['related_images']['name'][$i];
                       $size = $_FILES['related_images']['size'][$i];
       
                       list($txt, $ext) = explode(".", $name);
                       //$file= time().substr(str_replace(" ", "_", $txt), 0);
                       $file= substr(str_replace(" ", "_", $txt), 0);
                       $info = pathinfo($file);
                       $filename = $file.".".$ext;
                       $modifiedFileName = $_dir . $filename;
                       if(move_uploaded_file($_FILES['related_images']['tmp_name'][$i], $_dir.$filename)) 
                       { 
                          date_default_timezone_set ("Asia/Calcutta");
                          $currentdate=date("d M Y");
                          //$file_name_all.=$filename."*";
                          $conn->query("INSERT into product_images (`proid`, `pro_images`) VALUES('".$imid."', '".addslashes($modifiedFileName)."'); ");
                       }
                   }
                //$filepath = rtrim($file_name_all, '*');              
                }           
            }
            
            echo 'productupdated';
   
    } 
    
    
    
    
    //  New Member Registration 
    if(isset($_POST['action']) && $_POST['action'] == "newmemberprofile") {
      
       $email = $_POST["emailid"];
       if (!filter_var($email, FILTER_VALIDATE_EMAIL) === false) {
           
             $q=$conn->query("select userid FROM userlogin where emailid = '$email' or mobileno='".$_POST["mobileno"]."'");
             $count=$q->num_rows; 
             $r=$q->fetch_assoc();            
			
            if($count > 0) { 
                echo 'emailexists';
            
            }else {
                $cipherPassword  = encrypt($_POST["password"], "This is my secret code");
                $conn->query("INSERT INTO `userlogin` (`fullname`, `emailid`, `password`, `mobileno`, `verified_email`, `requestToken`, `regdated`) 
               VALUES ('".$conn->real_escape_string($_POST["fullname"])."', '".$conn->real_escape_string($_POST["emailid"])."',
                '".$cipherPassword."', '".$conn->real_escape_string($_POST["mobileno"])."', 0, '$autoGeneratedToken', '$currentDate')");        
               	                      
                   
				   /////////////////////////////////////////////////////////////////////////////////////////////////////
		//$my=$ord;	
$mobileNo=$_POST["mobileno"];
 $xml_data ='<?xml version="1.0"?>
<parent>

<child>
<user>ashraf7</user>
<key>54d71c002bXX</key>
<mobile>+91'.$mobileNo.'</mobile>
<message>Dear '.$_POST["fullname"].' Thank you for Signing with hu7.co Online Store.</message>
<accusage>2</accusage>
<senderid>HUSEVN</senderid>
</child>
</parent>';

$URL = "http://mobicomm.dove-sms.com/mobicomm/submitsms.jsp?"; 

			$ch = curl_init($URL);
			curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
			curl_setopt($ch, CURLOPT_POST, 1);
			curl_setopt($ch, CURLOPT_ENCODING, 'UTF-8');
			curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/xml'));
			curl_setopt($ch, CURLOPT_POSTFIELDS, "$xml_data");
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			$output = curl_exec($ch);
			curl_close($ch);

//print_r($output); 
 echo "registrationdone";
                        $evtstr='<table width="740"  style="border:#666666; size:2px;" align="center" cellpadding="10" cellspacing="0" bgcolor="#666666"  >
  <tr>
    <td valign="top"><table width="94%" border="0" cellspacing="0" cellpadding="0"  align="center"  style="border:#666666; size:2px;" >
      <tr>
        <td><img src="http://hu7.co/images/logo.png" style="width:200px" /><br><br></td>
      </tr>
      
      
      <tr>
        <td><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td height="122" valign="top"><table width="100%" border="0" cellpadding="8" cellspacing="0" bgcolor="#FFFFFF">
              <tr valign="top">
                <td width="50%"><table width="100%" border="0" cellpadding="6" cellspacing="0" bgcolor="#FFFFFF">
                    <tr>
                      <td colspan="4" valign="top" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; color: #003300;"><p><span style="font-size:16px;font-weight: bold;color: #333333;"></span></p>
					  </td>
  </tr>
					  <tr>
                      <td width="60%" colspan="4" valign="top" style="font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; color: #003300;"><p><span style="font-size:16px;font-weight: bold;color: #333333;">Query  detail :</span></p>
                        <p>';
$evtstr1.='</p></td>
                    </tr>  
                    </tr>  
                   
                </table></td>
              </tr>
              
            </table></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td bgcolor="#666666"><table width="100%" border="0" cellpadding="10" cellspacing="0" bgcolor="#666666">
          <tr>
            <td style="font-family: Verdana, Arial, Helvetica, sans-serif;font-size: 12px;color: #000000;"><div align="center" style="style4">

	

</h6>
Mobile No:-  +91-9891-451-777<br>

Email:- hu7onlineshop@gmail.com
 
</div></td>
          </tr>
        </table></td>
      </tr>
      
    </table></td>
  </tr>
</table>';
			
				///////////////////////////////////////////sms Generation////////////////////////////
				
									$to=$_REQUEST['emailid'];
                                    $from = "hu7onlineshop@gmail.com";
                                    $subject=$_REQUEST['email']; 
									$msg.='Name: '.$_REQUEST['fullname'].'<br><br>';	
				                    $msg.='Email: '.$_REQUEST['emailid'].'<br><br>';
                                    $msg.='password: '.$_REQUEST['password'].'<br><br>';																	
							     	 $message=$evtstr.$msg.$evtstr1;
									$headers  = "MIME-Version: 1.0\r\n";
									$headers .= "Content-type: text/html; charset=iso-8859-1\r\n";
									$headers .= "From:$from\r\n";
									@mail($to, $subject, $message, $headers);
                    
                    
                    /////////////////////////////////////////Site Admin/////////////////////////////////////////////////////////////
                    $adminto="hu7onlineshop@gmail.com";
                    $adminfrom=$_REQUEST['emailid'];
                    $querysubject=$_REQUEST['emailid']; 
                    $adminheaders  = "MIME-Version: 1.0\r\n";
                    $adminheaders .= "Content-type: text/html; charset=iso-8859-1\r\n";
                    $adminheaders .= "From:$adminfrom\r\n";                   
                    @mail($adminto, $subject, $message, $adminheaders);
                    
                    //////////////////////////////////////////////////////////////////////////////////////////////////////
				
				
				
				
				
				
				
				
				
				
				
				
				
				/////////////////////////////////////////////////////////////////////////////////////////////////
	
                   
            }
        } else {
        
             echo 'invalidemailaddress';
        
        }
    } 
    
    
    //Member Login
    if(isSet($_POST['action']) && $_POST['action'] == "memberlogin") {
	    
        $username         = addslashes($_POST['username']); 
        $password         = addslashes($_POST['password']);
                		
        $cipherPassword  = encrypt($password, "This is my secret code");

		$result = $conn->query("SELECT userid, emailid, fullname FROM userlogin WHERE ( emailid='$username' ) and password='$cipherPassword'");
		$count=$result->num_rows;

		$row=$result->fetch_assoc();
	
		if($count==1) {
		      
            
            //remove previous active session of perticular user 
            $result1 = $conn->query("SELECT user_logid FROM user_log WHERE userid = '".$row['userid']."' and is_active = '1'");
            $count1=$result1->num_rows; 
            $row1=$result1->fetch_assoc();
            
            if($count1==1) {
               
               $conn->query("UPDATE user_log SET end_session='".$currentDate."', is_active='0' WHERE user_logid='".$row1['user_logid']."'");
            }
            
              
    		$_SESSION['uuserid']             = $row['userid'];
    		$_SESSION['uname']               = $row['fullname'];
			$_SESSION['sess_webmail']               = $row['emailid'];
            $_SESSION['uautoSessionToken']   = $autoGeneratedToken;
            $_SESSION['ulogintype']   	     = 'member';
            			
    		//entering data into  log     		
    		$conn->query("INSERT INTO user_log (userid, active_session, is_active, loginToken) VALUES ('".$_SESSION['uuserid']."', '$currentDate', '1', '".$_SESSION['uautoSessionToken']."')");
			
			
            echo 'loginsuccess';
          
		}else {
		     
            echo 'loginnotsuccess';  
          
		}

	}    
    
    
     //  Update Member Registration 
    if(isset($_POST['action']) && $_POST['action'] == "updatememberprofile") {
        
        $conn->query("UPDATE `userlogin` SET `fullname`='".$conn->real_escape_string($_POST["fullname"])."', 
        `emailid`='".$conn->real_escape_string($_POST["emailid"])."', `mobileno`='".$conn->real_escape_string($_POST["mobileno"])."', `address`='".$conn->real_escape_string($_POST["address"])."', `pincode`='".$conn->real_escape_string($_POST["pincode"])."', `state`='".$_POST["state"]."', `city`='".$conn->real_escape_string($_POST["city"])."', `countryid`='".$conn->real_escape_string($_POST["country"])."' WHERE `userid`='".$_SESSION['uuserid']."'");        
       
         echo "memberprofileupdated";
  
    } 
    
    
    //  New Vendor Registration 
    if(isset($_POST['action']) && $_POST['action'] == "newvendorprofile") {
      
       $email = $_POST["emailid"];
       if (!filter_var($email, FILTER_VALIDATE_EMAIL) === false) {
           
             $q=$conn->query("select vendorid FROM vendorlogin where emailid = '$email' or mobileno='".$_POST["mobileno"]."'");
             $count=$q->num_rows; 
             $r=$q->fetch_assoc();            
			
            if($count > 0) { 
                echo 'emailexists';
            
            }else {
                $cipherPassword  = encrypt($_POST["password"], "This is my secret code");
                $conn->query("INSERT INTO `vendorlogin` (`fullname`, `emailid`, `password`, `mobileno`, `verified_email`, `requestToken`, `regdated`, organisation_name, organisation_active_date) 
               VALUES ('".$conn->real_escape_string($_POST["fullname"])."', '".$conn->real_escape_string($_POST["emailid"])."',
                '".$cipherPassword."', '".$conn->real_escape_string($_POST["mobileno"])."', 0, '$autoGeneratedToken', '$currentDate', '".$conn->real_escape_string($_POST["organisationname"])."', '".$conn->real_escape_string($_POST["organisationdate"])."')");        
               	                      
                   echo "registrationdone";
                   
            }
        } else {
        
             echo 'invalidemailaddress';
        
        } 
    }     
    
    
    
    //Vendor Login
    if(isSet($_POST['action']) && $_POST['action'] == "vendorlogin") {
	    
        $username         = addslashes($_POST['username']); 
        $password         = addslashes($_POST['password']);
                		
        $cipherPassword  = encrypt($password, "This is my secret code");

		$result = $conn->query("SELECT vendorid, emailid, fullname FROM vendorlogin WHERE ( emailid='$username' ) and password='$cipherPassword'");
		$count=$result->num_rows;

		$row=$result->fetch_assoc();
	
		if($count==1) {
		      
            
            //remove previous active session of perticular user 
            $result1 = $conn->query("SELECT vendor_logid FROM vendor_log WHERE vendorid = '".$row['vendorid']."' and is_active = '1'");
            $count1=$result1->num_rows; 
            $row1=$result1->fetch_assoc();
            
            if($count1==1) {
               
               $conn->query("UPDATE vendor_log SET end_session='".$currentDate."', is_active='0' WHERE vendor_logid='".$row1['vendor_logid']."'");
            }
            
              
    		$_SESSION['vuserid']             = $row['vendorid'];
    		$_SESSION['vname']               = $row['fullname'];
            $_SESSION['vautoSessionToken']   = $autoGeneratedToken;
            $_SESSION['vlogintype']          = 'vendor';
            $_SESSION['eid']             = $row['emailid'];			
    		//entering data into  log     		
    		$conn->query("INSERT INTO vendor_log (vendorid, active_session, is_active, loginToken) VALUES ('".$_SESSION['vuserid']."', '$currentDate', '1', '".$_SESSION['vautoSessionToken']."')");
			
			
            echo 'loginsuccess';
          
		}else {
		     
            echo 'loginnotsuccess';  
          
		}

	}
    
    
    //  Update Vendor Registration 
    if(isset($_POST['action']) && $_POST['action'] == "updatevendorprofile") {
        
        $conn->query("UPDATE `vendorlogin` SET `fullname`='".$conn->real_escape_string($_POST["fullname"])."', `organisation_name`='".$conn->real_escape_string($_POST["organisationname"])."', `organisation_active_date`='".$conn->real_escape_string($_POST["organisationdate"])."', 
        `emailid`='".$conn->real_escape_string($_POST["emailid"])."', `mobileno`='".$conn->real_escape_string($_POST["mobileno"])."', `address`='".$conn->real_escape_string($_POST["address"])."', `pincode`='".$conn->real_escape_string($_POST["pincode"])."', `state`='".$_POST["state"]."', `city`='".$conn->real_escape_string($_POST["city"])."', `countryid`='".$conn->real_escape_string($_POST["country"])."' WHERE `vendorid`='".$_SESSION['vuserid']."'");        
       
         echo "vendorprofileupdated";
  
    } 
    
    
    //Check pincode
    if(isset($_POST['action']) && $_POST['action'] == "checkpincode") {
        
        $q=$conn->query("select count(*) as validpincode from pincodes_list where pincodes_number='".trim($_POST["pincode"])."'");
        $r=$q->fetch_assoc();
        
        if($r['validpincode'] > 0) {
            echo 'Available';
        }else {
            echo 'Not Available';
        }
    }
    
    
    //Search Brands
    if(isset($_POST['action']) && $_POST['action'] == "getbrandname"){
	   
       $brandname = $_POST['getbrandname']; 
       $brandcat = $_POST['brandcat']; 
       //$brandvalue = $_POST['brandvalue']; 
       //$brandid = $_POST['brandid'];
       
        if(!empty($brandname)) {
            
            $query=$conn->query("select brand_name from product_details where cid = '$brandcat' and brand_name like '%$brandname%' group by brand_name");
            while($row = $query->fetch_array()) {           
                 echo "                           
                      
                       <li><input type='checkbox' name='brand' value='".base64_decode($row['brand_name'])."' onClick='this.form.submit();' /> <label>". ucwords($row['brand_name']) ."</label></li>
                 ";                           
            }        
        
        }else {
            
            $query=$conn->query("select brand_name from product_details where cid = '$brandcat' group by brand_name");
            while($row = $query->fetch_array()) {           
                 echo "                           
                      
                       <li><input type='checkbox' name='brand' value='".base64_decode($row['brand_name'])."' onClick='this.form.submit();' /> <label>". ucwords($row['brand_name']) ."</label></li>
                 ";                           
            } 
        }
    }
    
    
    
    //Search products
    if(isset($_POST['action']) && $_POST['action'] == "searchproduct"){
	   
       $search = $_POST['search']; 
              
        if(!empty($search)) {
            
            $query=$conn->query("select * from product_details where product_title like '%$search%' or product_name like '%$search%'");
            while($row = $query->fetch_array()) {           
                 echo "                           
                      
                       <a href='javascriipt:;'><div>
                        <img src=".$row['product_image']." style='width:50px; height:50px; float:left; margin-right:6px;' /><span>".ucwords($row['product_name'])."</span>&nbsp;Rs. ".$row['net_price']."
                        </div></a>

                 ";                           
            }        
        
        }
    }
    
    
    
    //Delete session cart products
    //print_r($_SESSION['products'][9]);
    if(isset($_POST['action']) && $_POST['action'] == "deletepro") {    
        $pid = $_POST['pid'];
        unset($_SESSION['products'][$pid]);
    }
    
    
    //Update products qty
    if(isset($_POST['action']) && $_POST['action'] == "updateproqty") {    
        $pid = $_POST['proid'];
        $pqty = $_POST['product_qty'];
        
       
        foreach($_POST as $key => $value){
		  $new_product[$key] = filter_var($value, FILTER_SANITIZE_STRING); //create a new product array 
        }
    
        //we need to get product name and price from database.
    	$statement = $conn->query("SELECT product_title, net_price FROM product_details WHERE proid='".$pid."' LIMIT 1");
        while($r=$statement->fetch_array()) {
            $new_product["product_title"] = $r['product_title']; //fetch product name from database
    		$new_product["net_price"] = $r['net_price'];;  //fetch product price from database
            
            if(isset($_SESSION["products"])){  //if session var already exist
    			if(isset($_SESSION["products"][$new_product['proid']])) //check item exist in products array
    			{
    				unset($_SESSION["products"][$new_product['proid']]); //unset old item
    			}			
            }
            $_SESSION["products"][$new_product['proid']] = $new_product;	//update products with new item array	
        }
        
        echo 'productupdated';
        
    }
    
    //Apply Promo Codes
    if(isset($_POST['action']) && $_POST['action'] == "applypromocode") {
    	
        $currentDate1 = date("Y-m-d"); 
            
        $promocode = $_POST['promocode'];
        $promocode = strtoupper($promocode);
        $_SESSION['couponno']=$promocode;
        $finalamount = $_POST['finalamount'];
        
        $query=$conn->query("select * from appliedpromocodes where promo_code = '$promocode'");
        $num = $query->num_rows;
        $row = $query->fetch_assoc();
    
            if($num > 0) {
                
                 $validfrom = $row['valid_from'];
                 $validto = $row['valid_to'];
                 $promocode = $row['promo_code'];
                 $amount = $row['amount'];
                 $totaltimes = $row['totaltimes'];
                 $status = $row['status'];  
                 $id = $row['couponid'];       
                 
                 if($status == 'InActive') {
                    
                    $status1 = 'promocodeinactive'; 
                    $status2 = '0';
                    $status3 = '0';
                    $status4 = '0';
                    $status5 = $finalamount;
                 }
                 
                 if(($status == 'Active') && ($finalamount < $amount) ) {
                     
                     $status1 = 'lesstotalamount'; 
                     $status2 = '0';
                     $status3 = '0';
                     $status4 = $amount; 
                     $status5 = $finalamount;
                 } 
                 
                 if(($status == 'Active') && ($finalamount > $amount) && ($currentDate1 > $validto) ) {
                     
                     $status1 = 'promocodeexpired'; 
                     $status2 = '0';
                     $status3 = '0';
                     $status4 = '0'; 
                     $status5 = $finalamount;
                 }
                 
                 if(($status == 'Active') && ($finalamount > $amount) && ($currentDate1 <= $validto) ) {
                     
                     $totalfinal_amount = $finalamount - $amount;
                     $status1 = 'promocodeactive'; 
                     $status2 = '1';
                     $status3 = $id;
                     $status4 = '1';
                     $status5 = $totalfinal_amount;   
                 } 
            
            }else {        
       
                $status1 = 'invalidpromocode'; 
                $status2 = '0';
                $status3 = '0';
                $status4 = '0'; 
                $status5 = $finalamount;
            }
        
            $arr = array();
            $arr[0] = $status1;
            $arr[1] = $status2; 
            $arr[2] = $status3; 
            $arr[3] = $status4;     
            $arr[4] = $status5;            
            echo json_encode($arr);
            exit();         
    }
    
    
    //Admin Orders
     if(isset($_POST['userpaymentid']) && $_POST['action'] == 'getupdatedorders') {
        
        $conn->query("UPDATE `userpaymentdetails` SET `order_status`='off' WHERE `userpaymentid`='".$_POST['userpaymentid']."'");
        
        echo 'orderupdated';
     }//else {
        
        //echo 'invalidpaymentid';
     //}  
    
    
     if(isset($_POST['getid']) && $_POST['action'] == 'getupdatedordersref') {
        
        $getid = $_POST['getid'];
        $getvalue = $_POST['getvalue'];
        
        $conn->query("UPDATE `userpaymentdetails` SET `refcomment`='$getvalue' WHERE `userpaymentid`='".$getid."'");
        
        echo $getvalue;
    }   

?>